### ISSUE TITLE
How do I access the guestbook example?

### ISSUE THREAD

**Issue by Industrial** [pires/kubernetes-vagrant-coreos-cluster#128]
Hi.

I'm new to Kubernetes (and CoreOS and Docker) and I'd like to see if I can get my Node.js apps running in Pods eventually. Right now I've gotten Kubernetes to run on linux (desktop pc) with this repo. I have ran the guestbook examplebut I'm not sure now how I access the HTTP service / website.

**Comment by mdevilliers** [comment]
Hey

The key information you need is in the https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/services.md#external-services

This explains the different ways you can expose your service.

Looking at the latest definition for the frontend-service.json -

```
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    name: frontend
```

The bit you need to pay attention to is the commented out type attribute. I would change this to 'NodePort' which would mean that the guestbook app would be accessible from each of the minions on a random port. Changing the attribute to 'LoadBalancer' would of course do this as well however the service wouldn't be load balanced in our instance.

To find out the port use kubectl and the describe command e.g.

```
kubectl describe services {servicename} 
```

Hope this helps,

Mark
