### ISSUE TITLE
some manifests yaml has parse errors / kube 1.5.2

### ISSUE THREAD

**Issue by remoe** [pires/kubernetes-vagrant-coreos-cluster#236]
When one validate the yaml of master-proxy and master-controller-manager with kubectl create -f ... then it throws a 'name' parsing error. To fix this:

```yaml
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
```

TO

```yaml
  volumes:
  - name: ssl-certs-kubernetes
    hostPath:
      path: /etc/kubernetes/ssl    
  - name: ssl-certs-host
    hostPath:
      path: /usr/share/ca-certificates
```
