### ISSUE TITLE
Persistant Volumes are not created

### ISSUE THREAD

**Issue by patvdleer** [pires/kubernetes-vagrant-coreos-cluster#272]
I'm not sure this is related to this specific project but it look like the persistent volumes aren't created dynamically. I've added the following StorageClasses but once I deploy a pod with a persistent volume claim the volume isn't created.

```
USE_KUBE_UI=true MASTER_CPUS=1 NODE_MEM=4096 MASTER_MEM=2048 NODE_CPUS=1 NODES=5 vagrant up
```

```yml
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: "EnsureExists"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: slow
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fsType: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-postgres
  namespace: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```
